### ISSUE TITLE
有一个Bug请问一下

### ISSUE THREAD

**Issue by zzy-life** [peiyu7921/miniprogram-threejs-demo#1]
在开发者工具会报错
![image](https://user-images.githubusercontent.com/68179477/219040854-352fde59-c891-4512-a1be-f11858b28e59.png)
但是在真机调试和预览不会
请问您有什么头绪吗

**Comment by peiyu7921** [comment]
看一下文件权限问题？检查文件存不存在、覆盖下原文件重新试试？

**Comment by zzy-life** [comment]
![image](https://user-images.githubusercontent.com/68179477/219042067-b074b2eb-543a-4659-9b91-5ec4d63573c1.png)
文件在同一个项目里  在D盘  权限应该是有的  文件也存在  我刚才也覆盖了  没作用

**Comment by peiyu7921** [comment]
![image](https://user-images.githubusercontent.com/51526225/219044231-ba2a4e4a-5379-4067-9ea5-d6dc5b54cfed.png)
最好保持原本文件路径或者改下
[https://github.com/peiyu7921/miniprogram-threejs-demo/blob/89e9b1456709a817914e2f9dc987a0ce30721360/libs/drocoWorker.js#L905](url)
此处代码

**Comment by zzy-life** [comment]
这些地方我都修改了  ，我发现js这里只能用url链接加载，用本地路径会报错
![image](https://user-images.githubusercontent.com/68179477/219046304-0414b9de-4fc3-4e85-b131-ab6bc05c2acf.png)

![image](https://user-images.githubusercontent.com/68179477/219046421-0cec75d3-cee3-4882-8384-831925350df4.png)
下面这两个函数都是报错的  WXWebAssembly.instantiate显示权限被拒绝
![image](https://user-images.githubusercontent.com/68179477/219046534-3fc2a8df-ee72-4eab-b6c4-d8b5612c90cf.png)
![image](https://user-images.githubusercontent.com/68179477/219046555-1e72e7e6-a152-464f-a7e2-859d76c9c876.png)

**Comment by peiyu7921** [comment]
那查查小程序版本？不然也不好说了，有点时间没维护过了

**Comment by zzy-life** [comment]
感觉是微信开发者工具的bug&nbsp; 算了&nbsp; 我现在在用真机测试&nbsp; 本来也只是为了适配带纹理的gltf



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 晚上9:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [peiyu7921/miniprogram-threejs-demo] 有一个Bug请问一下 (Issue #1)

**Comment by zzy-life** [comment]
已经确认了是开发者工具的问题
